# Generated by Django 2.2.5 on 2019-09-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190918_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='Average_rating',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
