# Generated by Django 2.2.5 on 2019-09-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190918_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ManyToManyField(related_name='cartitems', to='api.Cart'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comments',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
