# Generated by Django 2.2.5 on 2019-09-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190919_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('Knet', 'Knet'), ('Visa', 'Visa'), ('MC', 'MC')], max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('cart', 'cart'), ('placed', 'Placed'), ('review', 'review'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='cart', max_length=120),
        ),
    ]
