# Generated by Django 2.2.5 on 2019-09-28 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190923_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='cart',
        ),
    ]
