# Generated by Django 2.2.5 on 2019-09-20 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cartitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='image',
        ),
    ]
