# Generated by Django 2.1.5 on 2019-09-14 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190914_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='state',
            new_name='house',
        ),
        migrations.RemoveField(
            model_name='order',
            name='street_address2',
        ),
        migrations.AddField(
            model_name='cart',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='block',
            field=models.IntegerField(default=20, max_length=255),
            preserve_default=False,
        ),
    ]
