# Generated by Django 2.2.5 on 2019-09-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_address_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='complete_Address',
        ),
        migrations.AddField(
            model_name='address',
            name='complete_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
