# Generated by Django 2.1.5 on 2019-09-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190914_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='block',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sound',
            field=models.FileField(blank=True, null=True, upload_to='sound/'),
        ),
    ]
