# Generated by Django 2.1.5 on 2019-09-14 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190914_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='number_of_items',
        ),
    ]
