# Generated by Django 2.1.5 on 2019-09-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20190915_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='block',
            field=models.IntegerField(default=1),
        ),
    ]
